[ "AppData/Roaming/talon/user/community" ]
    type = "git-repo"
    url = "https://github.com/ProfDoof/community.git"
    clone.args = ["-b", "new_help_engine"] 
    refreshPeriod = "24h"
[ "AppData/Roaming/talon/user/rango-talon" ]
    type = "git-repo"
    url = "https://github.com/david-tejada/rango-talon.git"
    refreshPeriod = "24h"
[ "AppData/Roaming/talon/user/cursorless-talon" ]
    type = "git-repo"
    url = "https://github.com/cursorless-dev/cursorless-talon.git"
    refreshPeriod = "24h"
[ "AppData/Roaming/talon/user/talonhud" ]
    type = "git-repo"
    url = "https://github.com/chaosparrot/talon_hud.git"
    refreshPeriod = "24h"
[ "AppData/Roaming/talon/user/speak-the-spire-talon" ]
    type = "git-repo"
    url = "https://github.com/brollin/speak-the-spire-talon.git"
    refreshPeriod = "24h"
[ "AppData/Roaming/talon/user/talon-filetree-commands" ]
    type = "git-repo"
    url = "https://github.com/paul-schaaf/talon-filetree-commands.git"
    refreshPeriod = "24h"
